// App global state
const state = {
    model: null,
    players: [],
    selectedPlayer: null,
    isModelLoaded: false,
    arePlayersLoaded: false
};

// DOM Elements
const els = {
    states: {
        loading: document.getElementById('state-loading'),
        search: document.getElementById('state-search'),
        result: document.getElementById('state-result')
    },
    search: {
        select: document.getElementById('player-select'),
        btnAnalyze: document.getElementById('btn-predict')
    },
    result: {
        teamLogo: document.getElementById('res-team-logo'),
        photo: document.getElementById('res-photo'),
        name: document.getElementById('res-name'),
        stats: document.getElementById('res-stats'),
        // Y1
        tierY1: document.getElementById('res-tier-y1'),
        confY1: document.getElementById('res-conf-y1'),
        descY1: document.getElementById('res-desc-y1'),
        // Y2
        tierY2: document.getElementById('res-tier-y2'),
        confY2: document.getElementById('res-conf-y2'),
        descY2: document.getElementById('res-desc-y2'),
        btnReset: document.getElementById('btn-reset')
    }
};

// Config: Tiers and Thresholds
const TIERS = {
    0: { label: 'S', desc: 'Talento Geracional. Trajetória de Hall da Fama.', color: 'var(--tier-s-color)' },
    1: { label: 'A', desc: 'Calibre All-NBA. Pilar da Franquia.', color: 'var(--tier-a-color)' },
    2: { label: 'B', desc: 'Titular Sólido / Nível All-Star.', color: 'var(--tier-b-color)' },
    3: { label: 'C', desc: 'Jogador de Rotação.', color: 'var(--tier-c-color)' },
    4: { label: 'Bust', desc: 'Projeção decepcionante baseada nas estatísticas de novato.', color: 'var(--tier-bust-color)' }
};

// Initialize App
async function init() {
    try {
        console.log("Loading TensorFlow model...");
        // Load generated model topology and weights
        state.model = await tf.loadLayersModel('data/model.json');
        state.isModelLoaded = true;
        
        console.log("Loading players knowledge base...");
        // Fetch players data generated by CI pipeline
        const response = await fetch('data/players.json');
        state.players = await response.json();
        
        state.arePlayersLoaded = true;

        populateSearch();
        switchState('search');
    } catch (err) {
        console.error("Initialization Failed:", err);
        els.states.loading.innerHTML = `<p style="color:red">Falha ao carregar o modelo de IA ou os dados.</p>`;
    }
}

function switchState(targetState) {
    Object.values(els.states).forEach(el => {
        el.classList.remove('active');
        el.classList.add('hidden');
    });
    
    els.states[targetState].classList.remove('hidden');
    // Using setTimeout to allow display:block to apply before opacity transition
    setTimeout(() => {
        els.states[targetState].classList.add('active');
    }, 10);
}

function populateSearch() {
    els.search.select.innerHTML = '<option value="" disabled selected>Selecione um Sophomore...</option>';
    
    state.players.forEach((p, index) => {
        const opt = document.createElement('option');
        opt.value = index;
        opt.textContent = p.name;
        els.search.select.appendChild(opt);
    });

    els.search.select.addEventListener('change', (e) => {
        state.selectedPlayer = state.players[e.target.value];
        els.search.btnAnalyze.disabled = false;
    });

    els.search.btnAnalyze.addEventListener('click', runPrediction);
}

async function runPrediction() {
    if (!state.selectedPlayer) return;
    
    els.search.btnAnalyze.disabled = true;
    els.search.btnAnalyze.textContent = "Analisando...";

    const p = state.selectedPlayer;

    try {
        // Evaluate Year 1
        const tY1 = tf.tensor2d([p.y1.features]);
        const predY1 = state.model.predict(tY1);
        const scoresY1 = await predY1.data();
        const classY1 = scoresY1.indexOf(Math.max(...scoresY1));
        const confY1 = Math.max(...scoresY1);
        tY1.dispose();
        predY1.dispose();

        // Evaluate Year 2 (if available)
        let classY2 = null;
        let confY2 = null;

        if (p.y2 && p.y2.features) {
            const tY2 = tf.tensor2d([p.y2.features]);
            const predY2 = state.model.predict(tY2);
            const scoresY2 = await predY2.data();
            classY2 = scoresY2.indexOf(Math.max(...scoresY2));
            confY2 = Math.max(...scoresY2);
            tY2.dispose();
            predY2.dispose();
        }

        showResult(p, classY1, confY1, classY2, confY2);
    } catch (err) {
        console.error("Prediction Error:", err);
        alert("Falha ao analisar a trajetória.");
    } finally {
        els.search.btnAnalyze.disabled = false;
        els.search.btnAnalyze.textContent = "Analisar Teto de Carreira";
    }
}

function showResult(player, classY1, confY1, classY2, confY2) {
    // Populate UI Core
    els.result.name.textContent = player.name;
    
    // Show Y2 stats if they exist, otherwise fallback to Y1 (they might be out for the season)
    const stats = player.y2 ? player.y2.stats_raw : player.y1.stats_raw;
    els.result.stats.textContent = `${stats.PTS} PTS | ${stats.TRB} TRB | ${stats.AST} AST | ${(stats.TS_PERC * 100).toFixed(1)} TS%`;
    
    els.result.photo.src = `https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/${player.id}.png`;
    els.result.teamLogo.src = `https://cdn.nba.com/logos/nba/${player.teamId}/global/L/logo.svg`;

    // Tier Display Year 1
    const tierInfoY1 = TIERS[classY1];
    els.result.tierY1.textContent = tierInfoY1.label;
    els.result.tierY1.setAttribute('data-tier', tierInfoY1.label === 'Bust' ? 'Bust' : tierInfoY1.label);
    els.result.confY1.textContent = `${(confY1 * 100).toFixed(1)}%`;
    els.result.descY1.textContent = tierInfoY1.desc;

    // Tier Display Year 2
    if (classY2 !== null && confY2 !== null) {
        const tierInfoY2 = TIERS[classY2];
        els.result.tierY2.textContent = tierInfoY2.label;
        els.result.tierY2.setAttribute('data-tier', tierInfoY2.label === 'Bust' ? 'Bust' : tierInfoY2.label);
        els.result.confY2.textContent = `${(confY2 * 100).toFixed(1)}%`;
        els.result.descY2.textContent = tierInfoY2.desc;
    } else {
        els.result.tierY2.textContent = "N/A";
        els.result.tierY2.setAttribute('data-tier', 'Bust'); // Use grey for N/A
        els.result.confY2.textContent = "-";
        els.result.descY2.textContent = "Sem dados suficientes na 2ª temporada.";
    }

    switchState('result');
}

// Reset button
els.result.btnReset.addEventListener('click', () => {
    els.search.select.value = "";
    state.selectedPlayer = null;
    els.search.btnAnalyze.disabled = true;
    switchState('search');
});

// Boot app
document.addEventListener('DOMContentLoaded', init);
